import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TextLogo from "../components/TextLogo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AI Sales Assistant",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div
          style={{
            //backgroundColor: 'var(--primary-bg)',
            backgroundColor:'#ffffff',
            padding: "1rem",
            borderBottom: "1px solid #ffffffff",
            position: "fixed",
            top: 0,
            width: "100%",
            zIndex: 1000,
          }}
        >
          <TextLogo />
        </div>

        <main >{children}</main>

      </body>
    </html>
  );
}