"""Make search_id auto-increment

Revision ID: 91a9398c1ef0
Revises: 23892dd86da8
Create Date: 2025-09-12 22:32:42.497036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a9398c1ef0'
down_revision: Union[str, Sequence[str], None] = '23892dd86da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Alter the column to be auto-incrementing (PostgreSQL 10+)
    op.execute(
        """
        ALTER TABLE search_history
        ALTER COLUMN search_id
        ADD GENERATED BY DEFAULT AS IDENTITY
        """
    )


def downgrade() -> None:
    # Remove identity (revert to normal integer column)
    op.execute(
        """
        ALTER TABLE search_history
        ALTER COLUMN search_id
        DROP IDENTITY IF EXISTS
        """
    )

