"""add scraped_at column to raw_documents

Revision ID: baca3fa31e6b
Revises: 91a9398c1ef0
Create Date: 2025-09-15 23:02:04.805628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baca3fa31e6b'
down_revision: Union[str, Sequence[str], None] = '91a9398c1ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_documents', sa.Column('scraped_at', sa.TIMESTAMP(), nullable=True))
    op.create_index(op.f('ix_raw_documents_id'), 'raw_documents', ['id'], unique=False)
    op.drop_constraint(op.f('raw_documents_competitor_id_fkey'), 'raw_documents', type_='foreignkey')
    op.create_foreign_key(None, 'raw_documents', 'competitors', ['competitor_id'], ['competitor_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'raw_documents', type_='foreignkey')
    op.create_foreign_key(op.f('raw_documents_competitor_id_fkey'), 'raw_documents', 'competitors', ['competitor_id'], ['competitor_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_raw_documents_id'), table_name='raw_documents')
    op.drop_column('raw_documents', 'scraped_at')
    # ### end Alembic commands ###
