import { Geist, Geist_Mono } from "next/font/google";
//import "./globals.css";
import Navbar from '../../components/Navbar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "AI Sales Assistant",
  description: "Generated by Next.js",
};

export default function AuthLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        <main style={{ paddingTop: "3.35rem" }}>{children}</main>
      </body>
    </html>
  );
}